version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    env_file: ./.env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PW
      - POSTGRES_DB=$PG_DB
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  weather-tracker-api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: npm run start:dev
    env_file: ./.env
    environment:
      - NODE_ENV=$NODE_ENV
      - LOG_LEVEL=$LOG_LEVEL
      - SERVER_PORT=$SERVER_PORT
      - DEBUG_ORM_SQL=$DEBUG_ORM_SQL
      - PG_HOST=postgres
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
      - PG_PW=$PG_PW
      - PG_DB=$PG_DB
    depends_on:
      - postgres

volumes:
  postgres-data:

